{% set version = "2.0-1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-snpassoc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SNPassoc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SNPassoc/SNPassoc_{{ version }}.tar.gz
  sha256: b71b1b79490034aa7ef2931eae76a64c53ea79c86676499776db20bf72077669

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-haplo.stats
    - r-mvtnorm
    - r-plyr
    - r-poisbinom
    - r-survival
    - r-tidyr
  run:
    - r-base
    - r-ggplot2
    - r-haplo.stats
    - r-mvtnorm
    - r-plyr
    - r-poisbinom
    - r-survival
    - r-tidyr

test:
  commands:
    - $R -e "library('SNPassoc')"           # [not win]
    - "\"%R%\" -e \"library('SNPassoc')\""  # [win]

about:
  home: http://www.creal.cat/jrgonzalez/software.htm
  license: GPL-2.0-or-later
  summary: 'This package carries out most common analysis when performing whole genome association studies. These analyses include descriptive statistics and exploratory analysis of missing values, calculation of Hardy-Weinberg equilibrium, analysis of association based on generalized linear models (either for quantitative
    or binary traits), and analysis of multiple SNPs (haplotype and epistasis analysis). Permutation test and related tests (sum statistic and truncated product) are also implemented. Max-statistic and genetic risk-allele score exact distributions are also possible to be estimated. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
