travis:
  secure:
    BINSTAR_TOKEN: e2DmQlB7seD1qG/5foXhn0ZBicd9A+b/56qIPQWlVSGHurMtOpHIbU8+iU9mdsevZESFe/m/5tnBDDcgLdzzt14izAtjljKMRfdscHAnmavmSZtSY03PndQ6t/ZnNfjTYwa87DrP2QEO+lTWvscurtiE6QJn82UJFj1dS4KWkW20uA0giUvljqdJjBocFnUXthLM0ulxIOLkPqP/mc9bES67wa/RY2y2nuRsmRCf9Aq0aoN0VTWFpCHQS4AAJI66O1NJafoYTwwFwNi7j508bmGTRs6gE+c8BmcOONkpIRsmbLGdZIT6kTYN11BkOpaF3UrMZovcTEaPlSu/iUXSJHCibLrk2o7plEGgkvWLovwvtXyRO8aexJs+S/6uxu1eEFAI0w2RvVgkjnT2tnctIuRPgwzncKJhEDtnoDTH7ReLSJEVo/TdbM1yNqvNA3z5Y1u6da8grvxt/qLYgY2Y3Lsr8YWTcyI4xbhGQZA8EsDwFSeQSzoV4UZc/wH2Wls110Zdu1evMAf6ufXnqA37cgClKW3aaYg14fKuQuZp6VbRirlZ25XYGNdY2NLp9DJIcoAc2N6gbCXuIh1daK46wSeX1m+R9rzzTrF45P9ig2DSZi2hze4jkdGQUnF0yzam0EJgvF69nG6ldjbVybMtegOjhoTQRu0N7+8yAJCg34Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
