travis:
  secure:
    BINSTAR_TOKEN: NbRbHS2vdU8IxBe5C1ENnUUaLtVIjxcUKPMefntzGmCzknl3zZ2ganHAHx79I7/1UYqr43hsQhg3Ff3cX4tyB5UmxyaJEFckmv/erdZkCH6EzHe2rNV2c6g+qxMosV2SSo+OxgSWpYNSF6MAOU9ISDIp3wBsAt2itlVl64d1dcJ09P30oi2Szw1j8CqcMRVJmfN/VrNmZpg8DWIqPa3TJNZxGKQ5wmWaY/BdKjXXQGY0BpcUCigY8UREUiGE0+Z0iWY6eyQuknE6JULnYRjwjz/6mzzj/ZOlHtV//cvBP1C6iqrk/98pW6eZMj2FqBzsTI922VSjXIUhI3ebru1Pr/A5urnnSMtqKwEvqJJbM0l4JWIfzam8gKZgIJNRnlrse2kLGNej/j/MCSwAVqiYn6770Vpci/3pvgyh1A4NuwPcUdm/X1GDVt5mspFGDMXzqcsf9mnWL+xg5ljmcWwek5xicKXL4JVrRIXEPHlGKUj11Y6zHyFVjKsg2HY4ZWbP78xbsvbKvEtTNQ8SVscWydzvaa3Tn9qDxS17NK/10BlLSYkXuxwmb6QBx5nA37RAH+Mk+Z+kaDIWFF19JGSn5mv6Bt89VUulnhbqFQp11nMGL5BPPjvA2jBNk0vLZ5QZBjAynqgjDyKUmAEIv+FRH57H5CDNt/QXG0gunzj9pHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
