travis:
  secure:
    BINSTAR_TOKEN: QgOsdUBM6nZkJy+n/n2+DORe/JPG1shAY9elZYhyjHx001QinYLt7m5G4wKvHItwJfxmSI/kvHKyrqrHCB2CQrc9zPu9/RWiNiiCEX7TSQBo+conkwTYmSNXEkDBoVFuAdUyQjiW5RtVFq3rg+C/Q0TyrNtQ3eIV9AUdiCVviH0lnAT7V5cAS3zPeD5ebp5GzyoD1TxOyNaMY0SLgpXuyayx864mYotiSRQGHRHIAhp31FeEeV54Cktv3vBdWNxlFL3hxo95kqLUKgGgN+PFISelW3qTfR6cUAqcd+xcuhEUrQmH9easMJSGqgIKwVePwvLtvVgxCQ2aA2N7cAfZe958jytggWRH+V1c9UZLZQ4oOY0E0s0yKG1WFBMv7ffK6hoELX/2IYKwUr4+45v2DfbJ185QuRioJk+L5Wg1Dg2vMSG+be0UErw6/tN/FR5G9NLogIXw2JwHVAR6jJc/tdlSl2mTEl5WopiYfU7Iv0+EOq4oJJp7OPuwzKzFF7s1sW7m7+Y6Z//FQnl15Bz1CgoUt0GhIGVE8Gd9jNP5adjoHtW1TdtEkBJmi/968E4aKtgGHWs9AlGvexfr+K8XiG47gSg9K8JA7rPG6Ua+e++Q4P6YATPZBcLugazYaeGOrzcYoVMEHB45cli5DBbt+5NbWXgDETKmWhxC/Zm9kIU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
