appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Hxfu3sMiSdZe3kcxihmbyCauxtekNCsuWLFc1h0fYGgI7KpQioViIxb8U3GftzafBj/wOvLo7lEHnKsa2i/4HOQQCbQ8tM9cc+7sUgvVw8qjP9qLUC3KFXUB36ckjU1nGDKJ/w5JnTmOnFPQonw4J1RNmCJrZ2oWr/yFP6INOp4TgAhkYIGDDqYwbU19dPXA9WY4aB2JPUO63kuAxBdTI/SJzutzatDnSUiF/DNvOgn3vIlwf0Qo/c2pLKXka3YpS2t53f5trv7k6EfWvM8db/LHB0MrF3lOAunOn2WH5lLDqM072+YkhxyJnaqtrOglCri7WXvorCXfS9f5bQ2aSvX319kKCJ6wKtBUfPZLM7pvjxArKddkyqNk3lGggCTK/+5AWeJs2/MphhxEnrTGX21IU2R2lOFjaBQk7dg4s9Y5GC9Ja8thHrUjz7LE0zCCn5TFIBOnOzg3K84+IW2JvlgwIf3GhPvFajHzqFk8taqEbm6q4sZCC57DT7yYTct6L1gO0MVt5o2wajNbxL5nb+QpAVF3cBZe6kgqZ/0CnkQ/naFI9VDpoppZHifhQd5b+oTcmh4JGB9i2UBMYxzJjpohAaLPdhxSe7lVubwbmcifIZD++T2XSi8d08fzQf6xBJVxU9+cypUuzZXhQKj7UHKTXBxVWSutpVtCx0sC+BE=
